# Generated by Django 5.0 on 2023-12-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_categoria_options_alter_itempedido_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('imagen', models.ImageField(upload_to='imagenes/')),
                ('activo', models.BooleanField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_ult_act', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(related_name='campaña', to='store.categoria')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Camapañas',
                'db_table': 'st_campana',
            },
        ),
    ]
