# Generated by Django 5.0.1 on 2024-01-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_campaña'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaña',
            options={'verbose_name': 'Campaña', 'verbose_name_plural': 'Campañas'},
        ),
    ]
