from django.urls import path

from . import views
from . import ingresos_views


urlpatterns = [
    path('', views.home, name='home'),
    path('signin/', views.do_signin, name='signin'),
    path('logout/', views.do_logout, name='logout'),
    path('portal/mi-empresa/', views.mi_empresa, name='mi_empresa'),
    path('portal/parametros/', views.parametros, name='parametros'),
    path('portal/cambiar-contrasena/', views.cambiar_contrasena, name='cambiar_contrasena'),
    path('portal/aceptar-documento-legal/', views.aceptar_documento_legal, name='aceptar_documento_legal'),
    path('portal/gastos/compras/', views.compras, name='compras'),
    path('portal/gastos/compras/pdf/', views.compras_pdf, name='compras_pdf'),
    path('portal/gastos/compras/excel/', views.compras_excel, name='compras_excel'),
    path('portal/gastos/notas-credito/', views.notas_credito, name='notas_credito'),
    path('portal/gastos/notas-credito/pdf/', views.notas_credito_pdf, name='notas_credito_pdf'),
    path('portal/gastos/notas-credito/excel/', views.notas_credito_excel, name='notas_credito_excel'),
    path('portal/gastos/listado-proveedores/', views.listado_proveedores, name='listado_proveedores'),
    path('portal/gastos/listado-proveedores/pdf/', views.listado_proveedores_pdf, name='listado_proveedores_pdf'),
    path('portal/gastos/listado-proveedores/excel/', views.listado_proveedores_excel, name='listado_proveedores_excel'),
    path('portal/ingresos/facturas/', views.ventas, name='ventas'),
    path('portal/ingresos/facturas/pdf/', views.ventas_pdf, name='ventas_pdf'),
    path('portal/ingresos/facturas/excel/', views.ventas_excel, name='ventas_excel'),
    path('portal/ingresos/notas-credito/', ingresos_views.ingresos_notas_credito, name='ingresos_notas_credito'),
    path('portal/ingresos/notas-credito/pdf/', ingresos_views.ingresos_notas_credito_pdf, name='ingresos_notas_credito_pdf'),
    path('portal/ingresos/notas-credito/excel/', ingresos_views.ingresos_notas_credito_excel, name='ingresos_notas_credito_excel'),
    path('portal/ingresos/listado-clientes/', views.listado_clientes, name='listado_clientes'),
    path('portal/ingresos/listado-clientes/pdf/', views.listado_clientes_pdf, name='listado_clientes_pdf'),
    path('portal/ingresos/listado-clientes/excel/', views.listado_clientes_excel, name='listado_clientes_excel'),
    path('portal/ingresos/productos-ice/', views.error_404, name='productos_ice'),
    path('portal/ingresos/registros-ice/', views.error_404, name='registros_ice'),
    path('portal/emitir/factura/', views.factura_emitir, name='factura_emitir'),
    path('portal/emitir/nota-credito/', views.nota_credito_emitir, name='nota_credito_emitir'),
    path('portal/emitir/guia-remision/', views.guia_remision_emitir, name='guia_remision_emitir'),
    path('portal/emitir/retencion/', views.retencion_emitir, name='retencion_emitir'),
    path('portal/emitir/liquidacion-compra/', views.liquidacion_compra_emitir, name='liquidacion_compra_emitir'),

    path('portal/emitir/nota-credito/buscar-sustento/', views.nota_credito_buscar_sustento, name='nota_credito_buscar_sustento'),

    path('portal/emitir/factura/buscar-cliente/', views.factura_buscar_cliente, name='factura_buscar_cliente'),
    path('portal/emitir/factura/buscar-productos/', views.factura_buscar_productos, name='factura_buscar_productos'),
    path('portal/laboral/roles-de-pago/', views.roles_pago, name='roles_pago'),
    path('portal/laboral/roles-de-pago/<int:numero>/', views.rol_pago_detalle, name='rol_pago_detalle'),
    path('portal/laboral/roles-de-pago/<int:numero>/pdf/', views.rol_pago_pdf, name='rol_pago_pdf'),
    path('portal/laboral/roles-de-pago/pdf/', views.roles_pago_pdf, name='roles_pago_pdf'),
    path('portal/laboral/roles-de-pago/excel/', views.roles_pago_excel, name='roles_pago_excel'),
    path('portal/laboral/trabajadores/', views.trabajadores, name='trabajadores'),
    path('portal/laboral/trabajadores/pdf/', views.trabajadores_pdf, name='trabajadores_pdf'),
    path('portal/laboral/trabajadores/excel/', views.trabajadores_excel, name='trabajadores_excel'),
    path('portal/laboral/trabajadores/<str:cedula>/pdf/', views.trabajador_pdf, name='trabajador_pdf'),
    path('portal/laboral/trabajadores/<str:cedula>/', views.trabajador_detalle, name='trabajador_detalle'),
    path('portal/', views.portal, name='portal'),
    path('about/', views.about, name='about'),
    path('contactanos/', views.contactanos, name='contactanos'),
    path('avisos-legales/', views.avisos_legales, name='avisos_legales'),
    path('servicios/', views.servicios, name='servicios'),
    path('blog/', views.blog, name='blog'),
    path('plantillas/', views.template_catalog, name='template_catalog'),
    path('plantillas/<slug:slug>/', views.template_preview, name='template_preview'),
]
