from django.urls import path

from . import views
from . import ingresos_views
from . import admin_views
from .admin_trabajadores_pdf import admin_trabajadores_pdf


urlpatterns = [
    path('', views.home, name='home'),
    path('suscribirse/', views.newsletter_subscribe, name='newsletter_subscribe'),
    path('signin/', views.do_signin, name='signin'),
    path('totalcounts/login/', admin_views.admin_login, name='admin_login'),
    path('totalcounts/logout/', admin_views.admin_logout, name='admin_logout'),
    path('internal/conta/worker-error/', admin_views.conta_worker_error, name='conta_worker_error'),
    path('internal/conta/certificado-ruc/', admin_views.conta_certificado_ruc, name='conta_certificado_ruc'),
    path('totalcounts/', admin_views.admin_dashboard, name='admin_dashboard'),
    path('totalcounts/conta/', admin_views.admin_conta, name='admin_conta'),
    path('totalcounts/conta/certificados-ruc/iniciar/', admin_views.admin_conta_certificados_ruc, name='admin_conta_certificados_ruc'),
    path('totalcounts/conta/sri/status/', admin_views.admin_conta_sri_status, name='admin_conta_sri_status'),
    path('totalcounts/conta/sri/cancelar/', admin_views.admin_conta_sri_cancelar, name='admin_conta_sri_cancelar'),
    path('totalcounts/clientes/', admin_views.admin_clientes, name='admin_clientes'),
    path('totalcounts/suscriptores/', admin_views.admin_suscriptores, name='admin_suscriptores'),
    path('totalcounts/contrasenas/', admin_views.admin_contrasenas, name='admin_contrasenas'),
    path('totalcounts/contrasenas/<str:ruc>/editar/', admin_views.admin_contrasenas_editar, name='admin_contrasenas_editar'),
    path('totalcounts/contrasenas/<str:ruc>/toggle-activo/', admin_views.admin_contrasenas_toggle_activo, name='admin_contrasenas_toggle_activo'),
    path('totalcounts/datos-usuario/', admin_views.admin_datos_usuario, name='admin_datos_usuario'),
    path('totalcounts/cambiar-contrasena/', admin_views.admin_cambiar_contrasena, name='admin_cambiar_contrasena'),
    path('totalcounts/workers/', admin_views.admin_workers, name='admin_workers'),
    path('totalcounts/foto-usuario/', admin_views.admin_foto_usuario, name='admin_foto_usuario'),
    path('totalcounts/clientes/<str:ruc>/', admin_views.admin_cliente, name='admin_cliente'),
    path('totalcounts/clientes/<str:ruc>/certificado-ruc/', admin_views.admin_cliente_certificado_ruc, name='admin_cliente_certificado_ruc'),
    path('totalcounts/clientes/<str:ruc>/documento-legal/<str:tipo>/', admin_views.admin_cliente_documento_legal, name='admin_cliente_documento_legal'),
    path('totalcounts/clientes/<str:ruc>/documentacion/', admin_views.admin_documentacion, name='admin_documentacion'),
    path('totalcounts/clientes/<str:ruc>/laboral/', admin_views.admin_laboral, name='admin_laboral'),
    path('totalcounts/clientes/<str:ruc>/laboral/trabajadores/', admin_views.admin_trabajadores, name='admin_trabajadores'),
    path('totalcounts/clientes/<str:ruc>/laboral/trabajadores/excel/', admin_views.admin_trabajadores_excel, name='admin_trabajadores_excel'),
    path('totalcounts/clientes/<str:ruc>/laboral/trabajadores/pdf/', admin_trabajadores_pdf, name='admin_trabajadores_pdf'),
    path('totalcounts/clientes/<str:ruc>/laboral/trabajadores/<str:cedula>/pdf/', admin_views.admin_trabajador_pdf, name='admin_trabajador_pdf'),
    path('totalcounts/clientes/<str:ruc>/laboral/trabajadores/<str:cedula>/', admin_views.admin_trabajador_detalle, name='admin_trabajador_detalle'),
    path('totalcounts/clientes/<str:ruc>/documentacion/compras/', admin_views.admin_compras, name='admin_compras'),
    path('totalcounts/clientes/<str:ruc>/documentacion/notas-credito-recibidas/', admin_views.admin_notas_credito_recibidas, name='admin_notas_credito_recibidas'),
    path('totalcounts/clientes/<str:ruc>/documentacion/notas-credito-recibidas/excel/', admin_views.admin_notas_credito_excel, name='admin_notas_credito_excel'),
    path('totalcounts/clientes/<str:ruc>/documentacion/notas-credito-recibidas/pdf/', admin_views.admin_notas_credito_pdf, name='admin_notas_credito_pdf'),
    path('totalcounts/clientes/<str:ruc>/documentacion/notas-credito-emitidas/', admin_views.admin_notas_credito_emitidas, name='admin_notas_credito_emitidas'),
    path('totalcounts/clientes/<str:ruc>/documentacion/notas-credito-emitidas/excel/', admin_views.admin_notas_credito_emitidas_excel, name='admin_notas_credito_emitidas_excel'),
    path('totalcounts/clientes/<str:ruc>/documentacion/notas-credito-emitidas/pdf/', admin_views.admin_notas_credito_emitidas_pdf, name='admin_notas_credito_emitidas_pdf'),
    path('totalcounts/clientes/<str:ruc>/documentacion/ventas/', admin_views.admin_ventas, name='admin_ventas'),
    path('totalcounts/clientes/<str:ruc>/documentacion/ventas/editar/', admin_views.admin_ventas_editar, name='admin_ventas_editar'),
    path('totalcounts/clientes/<str:ruc>/documentacion/ventas/excel/', admin_views.admin_ventas_excel, name='admin_ventas_excel'),
    path('totalcounts/clientes/<str:ruc>/documentacion/ventas/pdf/', admin_views.admin_ventas_pdf, name='admin_ventas_pdf'),
    path('totalcounts/clientes/<str:ruc>/documentacion/compras/editar/', admin_views.admin_compras_editar, name='admin_compras_editar'),
    path('totalcounts/clientes/<str:ruc>/documentacion/compras/excel/', admin_views.admin_compras_excel, name='admin_compras_excel'),
    path('totalcounts/clientes/<str:ruc>/documentacion/compras/pdf/', admin_views.admin_compras_pdf, name='admin_compras_pdf'),
    path('logout/', views.do_logout, name='logout'),
    path('portal/mi-empresa/', views.mi_empresa, name='mi_empresa'),
    path('portal/mi-empresa/certificado-ruc/', views.mi_empresa_certificado_ruc, name='mi_empresa_certificado_ruc'),
    path('portal/mi-empresa/documento-legal/<str:tipo>/', views.mi_empresa_documento_legal, name='mi_empresa_documento_legal'),
    path('portal/parametros/', views.parametros, name='parametros'),
    path('portal/cambiar-contrasena/', views.cambiar_contrasena, name='cambiar_contrasena'),
    path('portal/aceptar-documento-legal/', views.aceptar_documento_legal, name='aceptar_documento_legal'),
    path('portal/gastos/compras/', views.compras, name='compras'),
    path('portal/gastos/compras/pdf/', views.compras_pdf, name='compras_pdf'),
    path('portal/gastos/compras/excel/', views.compras_excel, name='compras_excel'),
    path('portal/gastos/notas-credito/', views.notas_credito, name='notas_credito'),
    path('portal/gastos/notas-credito/pdf/', views.notas_credito_pdf, name='notas_credito_pdf'),
    path('portal/gastos/notas-credito/excel/', views.notas_credito_excel, name='notas_credito_excel'),
    path('portal/gastos/listado-proveedores/', views.listado_proveedores, name='listado_proveedores'),
    path('portal/gastos/listado-proveedores/pdf/', views.listado_proveedores_pdf, name='listado_proveedores_pdf'),
    path('portal/gastos/listado-proveedores/excel/', views.listado_proveedores_excel, name='listado_proveedores_excel'),
    path('portal/ingresos/facturas/', views.ventas, name='ventas'),
    path('portal/ingresos/facturas/pdf/', views.ventas_pdf, name='ventas_pdf'),
    path('portal/ingresos/facturas/excel/', views.ventas_excel, name='ventas_excel'),
    path('portal/ingresos/notas-credito/', ingresos_views.ingresos_notas_credito, name='ingresos_notas_credito'),
    path('portal/ingresos/notas-credito/pdf/', ingresos_views.ingresos_notas_credito_pdf, name='ingresos_notas_credito_pdf'),
    path('portal/ingresos/notas-credito/excel/', ingresos_views.ingresos_notas_credito_excel, name='ingresos_notas_credito_excel'),
    path('portal/ingresos/listado-clientes/', views.listado_clientes, name='listado_clientes'),
    path('portal/ingresos/listado-clientes/pdf/', views.listado_clientes_pdf, name='listado_clientes_pdf'),
    path('portal/ingresos/listado-clientes/excel/', views.listado_clientes_excel, name='listado_clientes_excel'),
    path('portal/ingresos/productos-ice/', views.error_404, name='productos_ice'),
    path('portal/ingresos/registros-ice/', views.error_404, name='registros_ice'),
    path('portal/sri/anexos/', views.sri_anexos, name='sri_anexos'),
    path('administracion/sri/anexos/', views.sri_anexos_admin, name='sri_anexos_admin'),
    path('portal/emitir/factura/', views.factura_emitir, name='factura_emitir'),
    path('portal/emitir/nota-credito/', views.nota_credito_emitir, name='nota_credito_emitir'),
    path('portal/emitir/guia-remision/', views.guia_remision_emitir, name='guia_remision_emitir'),
    path('portal/emitir/retencion/', views.retencion_emitir, name='retencion_emitir'),
    path('portal/emitir/liquidacion-compra/', views.liquidacion_compra_emitir, name='liquidacion_compra_emitir'),

    path('portal/emitir/nota-credito/buscar-sustento/', views.nota_credito_buscar_sustento, name='nota_credito_buscar_sustento'),

    path('portal/emitir/factura/buscar-cliente/', views.factura_buscar_cliente, name='factura_buscar_cliente'),
    path('portal/emitir/factura/buscar-productos/', views.factura_buscar_productos, name='factura_buscar_productos'),
    path('portal/laboral/roles-de-pago/', views.roles_pago, name='roles_pago'),
    path('portal/laboral/roles-de-pago/<int:numero>/', views.rol_pago_detalle, name='rol_pago_detalle'),
    path('portal/laboral/roles-de-pago/<int:numero>/pdf/', views.rol_pago_pdf, name='rol_pago_pdf'),
    path('portal/laboral/roles-de-pago/pdf/', views.roles_pago_pdf, name='roles_pago_pdf'),
    path('portal/laboral/roles-de-pago/excel/', views.roles_pago_excel, name='roles_pago_excel'),
    path('portal/laboral/trabajadores/', views.trabajadores, name='trabajadores'),
    path('portal/laboral/trabajadores/pdf/', views.trabajadores_pdf, name='trabajadores_pdf'),
    path('portal/laboral/trabajadores/excel/', views.trabajadores_excel, name='trabajadores_excel'),
    path('portal/laboral/trabajadores/<str:cedula>/pdf/', views.trabajador_pdf, name='trabajador_pdf'),
    path('portal/laboral/trabajadores/<str:cedula>/', views.trabajador_detalle, name='trabajador_detalle'),
    path('portal/', views.portal, name='portal'),
    path('about/', views.about, name='about'),
    path('contactanos/', views.contactanos, name='contactanos'),
    path('avisos-legales/', views.avisos_legales, name='avisos_legales'),
    path('servicios/', views.servicios, name='servicios'),
    path('blog/', views.blog, name='blog'),
    path('plantillas/', views.template_catalog, name='template_catalog'),
    path('plantillas/<slug:slug>/', views.template_preview, name='template_preview'),
]
